docreatedata: true
docomp: true
ntrajectory: 8
T: "Float32"
params:
  D: 2
  lims: [0.0, 1.0]
  Re: 6000.0
  tburn: 0.5
  tsim: 5.0
  savefreq: 50
  ndns: 4096
  nles: [128]
  filters: ["FaceAverage()"]
  icfunc: "(setup, psolver, rng) -> random_field(setup, T(0); kp=20, psolver, rng)"
  method: "RKMethods.Wray3(; T)"
  bodyforce: "(dim, x, y, t) -> (dim == 1) * 5 * sinpi(8 * y)"
  issteadybodyforce: true
  processors: "(; log = timelogger(; nupdate=100))"
  Δt: 0.00005
seeds:
  dns: 123
  θ_start: 234
  prior: 345
  post: 456
closure:
  name: "cno_1"
  type: cno
  size: 128
  cutoff: 10
  channels: [24, 24, 24, 24, 2]
  activations: ["relu", "relu", "relu", "relu", "identity"]
  down_factors: [2, 2, 2, 2, 2]
  radii: [2, 2, 2, 2, 2]
  bottleneck_depths: [2, 2, 2, 2, 2]
  rng: "Xoshiro(seeds.θ_start)"
priori:
  dotrain: true
  nepoch: 5000
  batchsize: 64
  opt: "OptimiserChain(Adam(T(1.0e-2)), ClipGrad(1))"
  do_plot: false
  plot_train: false
posteriori:
  dotrain: true
  projectorders: "(ProjectOrder.Last, )"
  nepoch: 500
  opt: "OptimiserChain(Adam(T(1.0e-2)), ClipGrad(1))"
  nunroll: 5
  nunroll_valid: 10
  dt: T(5e-5)
  do_plot: false
  plot_train: false
