docreatedata: true
docomp: true
ntrajectory: 8
T: "Float32"
params:
  D: 2
  lims: [0.0, 1.0]
  Re: 6000.0
  tburn: 0.5
  tsim: 2.0
  savefreq: 100
  ndns: 64
  nles: [32]
  filters: ["FaceAverage()"]
  icfunc: "(setup, psolver, rng) -> random_field(setup, T(0); kp=20, psolver, rng)"
  method: "RKMethods.Wray3(; T)"
  bodyforce: "(dim, x, y, t) -> (dim == 1) * 5 * sinpi(8 * y)"
  issteadybodyforce: true
  processors: "(; log = timelogger(; nupdate=100))"
  Δt: 0.0001
seeds:
  dns: 123
  θ_start: 234
  prior: 345
  post: 456
closure:
  name: "attcnn_2"
  type: attentioncnn
  radii: [2, 2]
  channels: [24, 2]
  activations: ["relu", "identity"]
  use_bias: [true, false]
  use_attention: [true, false]
  emb_sizes: [124, 124]
  Ns: [40, 36]
  patch_sizes: [8, 6]
  n_heads: [4, 4]
  sum_attention: [false, false]
  rng: "Xoshiro(seeds.θ_start)"
priori:
  dotrain: true
  nepoch: 1000
  batchsize: 32
  opt: "OptimiserChain(Adam(T(1.0e-3)), ClipGrad(0.1))"
  do_plot: false
  plot_train: false
posteriori:
  dotrain: true
  projectorders: "(ProjectOrder.Last, )"
  nepoch: 10
  opt: "OptimiserChain(Adam(T(1.0e-3)), ClipGrad(0.1))"
  nunroll: 2
  nunroll_valid: 3
  dt: T(1e-4)
  do_plot: false
  plot_train: false
