docreatedata: true
docomp: true
ntrajectory: 8
T: "Float32"
params:
  D: 2
  lims: [0.0, 1.0]
  Re: 6000.0
  tburn: 1.5
  tsim: 2.0
  savefreq: 100
  ndns: 1024
  nles: [32]
  filters: ["FaceAverage()"]
  icfunc: "(setup, psolver, rng) -> random_field(setup, T(0); kp=20, psolver, rng)"
  method: "RKMethods.Wray3(; T)"
  bodyforce: "(dim, x, y, t) -> (dim == 1) * 5 * sinpi(8 * y)"
  issteadybodyforce: true
  processors: "(; log = timelogger(; nupdate=100))"
  Δt: 0.0001
seeds:
  dns: 11
  θ_start: 22
  prior: 33
  post: 44
closure:
  name: "cno_3"
  type: cno
  size: 32
  cutoff: 10
  channels: [24]
  activations: ["Lux.tanh_fast", "identity"]
  down_factors: [2]
  radii: [2]
  bottleneck_depths: [2, 2]
  rng: "Xoshiro(seeds.θ_start)"
priori:
  dotrain: true
  nepoch: 1000
  batchsize: 32
  opt: "OptimiserChain(Adam(T(1.0e-3)), ClipGrad(0.1))"
  do_plot: false
  plot_train: false
posteriori:
  dotrain: true
  projectorders: "(ProjectOrder.Last, )"
  nepoch: 100
  opt: "OptimiserChain(Adam(T(1.0e-3)), ClipGrad(0.1))"
  nunroll: 5
  nunroll_valid: 5
  dt: T(1e-4)
  do_plot: false
  plot_train: false
